name: Despliegue MkDocs
on:
  push:
    branches:
      - master # Cambia esto si tu rama principal se llama 'master'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Desplegar en GitHub Pages
        run: mkdocs gh-deploy --force